# Generated by Django 5.1.7 on 2025-05-18 14:26

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('city', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хетчбек'), ('suv', 'Позашляховик'), ('wagon', 'Універсал'), ('coupe', 'Купе'), ('convertible', 'Кабріолет'), ('van', 'Мінівен'), ('pickup', 'Пікап')], max_length=20)),
                ('drive_type', models.CharField(choices=[('fwd', 'Передній'), ('rwd', 'Задній'), ('awd', 'Повний'), ('4wd', '4WD')], max_length=10)),
                ('power', models.PositiveIntegerField(help_text='Потужність двигуна в к.с.')),
                ('transmission', models.CharField(choices=[('manual', 'Механічна'), ('automatic', 'Автоматична'), ('cvt', 'Варіатор'), ('semi-auto', 'Роботизована')], max_length=15)),
                ('color', models.CharField(choices=[('white', 'Білий'), ('black', 'Чорний'), ('silver', 'Срібний'), ('gray', 'Сірий'), ('red', 'Червоний'), ('blue', 'Синій'), ('green', 'Зелений'), ('yellow', 'Жовтий'), ('brown', 'Коричневий'), ('orange', 'Помаранчевий'), ('purple', 'Фіолетовий'), ('beige', 'Бежевий')], max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('door_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('had_accidents', models.BooleanField(default=False, help_text='Чи була машина в ДТП')),
                ('vin_code', models.CharField(blank=True, max_length=17, null=True)),
                ('main_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main_photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
