# Generated by Django 5.1.7 on 2025-05-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementphoto',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.advertisement'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['created_at', 'is_active'], name='cars_advert_created_1c64e0_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['brand', 'price'], name='cars_advert_brand_c051c4_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['year', 'price'], name='cars_advert_year_aa34e8_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['city', 'is_active'], name='cars_advert_city_6614be_idx'),
        ),
    ]
