<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-08 20:24
=======
# Generated by Django 5.1.7 on 2025-04-11 17:34
>>>>>>> 741d306 (finally-postgres-connected)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverstisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.brand'),
        ),
        migrations.AddField(
            model_name='carproduct',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.bodytype'),
        ),
        migrations.AddField(
            model_name='carproduct',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_products', to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='car_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='cars.carproduct'),
        ),
        migrations.AddField(
            model_name='carproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.color'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'model_name')},
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['created_at', 'is_active'], name='cars_advert_created_1c64e0_idx'),
        ),
        migrations.AddIndex(
            model_name='carproduct',
            index=models.Index(fields=['year', 'price'], name='cars_carpro_year_8f890b_idx'),
        ),
        migrations.AddIndex(
            model_name='carproduct',
            index=models.Index(fields=['mileage'], name='cars_carpro_mileage_05a48d_idx'),
        ),
    ]
